name: CI/CD
on: [push]

jobs:
  test:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.15'
      - name: NPM Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install
        run: CI=true npm ci
      - name: Code Climate - Setup
        # Install the Code Climate reporter in workspace
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Test
        run: npm run test
      # Upload test code coverage report to Code Climate (branch must be explicitly set)
      # - name: Code Climate - Report
      #   if: success()
      #   run: |
      #     export GIT_BRANCH="${GIT_BRANCH:-${GITHUB_REF:11}}"
      #     ./cc-test-reporter after-build
      #   env:
      #     CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      #     GIT_BRANCH: ${{ github.head_ref }}
